FROM python:3.10
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./secrets.toml /code/.streamlit/secrets.toml
COPY ./app /code/app
COPY ./config.yaml /code/config.yaml
CMD ["streamlit", "run", "app/Login.py", "--server.port=8501", "--server.address=0.0.0.0"]
