global:
  scrape_interval: 15s
  
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'car_service-prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['car_service-prometheus:9090']

  - job_name: 'car_service-backend'
    static_configs:
      - targets: ['car_service-backend:8000']

  - job_name: 'car_service-cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['car_service-cadvisor:8080']
